# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodePushRNSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CodePushRNSample
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'CodePushRNSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CodePushRNSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CodePushRNSample-tvOS

  target 'CodePushRNSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
